# Generated by Django 6.0 on 2025-12-29 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('time', models.IntegerField()),
                ('q1', models.CharField(default=False, max_length=250)),
                ('q2', models.CharField(default=False, max_length=250)),
                ('q3', models.CharField(default=False, max_length=250)),
                ('q4', models.CharField(default=False, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.questions')),
                ('tags', models.ManyToManyField(related_name='quizzes', to='app.tags')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('quizzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='app.quizzes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
